### ISSUE TITLE
HDPVR: Rebooting the system-under-test fails with "Device '/dev/video0' does not support video capture"

### ISSUE THREAD

**Issue by drothlis** [drothlis/stb-tester#139]
@szemate reports:

> Any test that turns off the set-top-box fails when the box is turned
> back on with:
> 
>     Traceback (most recent call last):
>     File "/usr/libexec/stbt/stbt-run", line 50, in <module>
>       execfile(args.script)
>     File "reboot.py", line 6, in <module>
>       power.cold_reboot()
>     File "/home/szemate/uitests/library/power.py", line 41, in cold_reboot
>       ensure_boot_sequence()
>     File "/home/szemate/uitests/library/power.py", line 55, in ensure_boot_sequence
>       timeout_secs=120)
>     File "/usr/libexec/stbt/stbt.py", line 520, in wait_for_match
>       image, timeout_secs, match_parameters=match_parameters):
>     File "/usr/libexec/stbt/stbt.py", line 349, in detect_match
>       for sample in _display.gst_samples(timeout_secs):
>     File "/usr/libexec/stbt/stbt.py", line 1253, in gst_samples
>       sample = self.get_sample(max(10, timeout_secs))
>     File "/usr/libexec/stbt/stbt.py", line 1237, in get_sample
>       raise UITestError(str(gst_sample))
>     UITestError: Device '/dev/video0' does not support video capture:
>     Device '/dev/video0' does not support video capture
>     gstv4l2object.c(2401): gst_v4l2_object_set_format ():
>     /GstPipeline:pipeline2/GstV4l2Src:v4l2src1:
>     Call to G_FMT failed: (Bad address)

**Comment by drothlis** [comment]
Closing as per @szemate's [comment|#issuecomment-45755094]. Thanks for reporting.
