### ISSUE TITLE
HDPVR: Occasional "Internal data flow error" upon startup

### ISSUE THREAD

**Issue by drothlis** [drothlis/stb-tester#140]
@szemate reports:

> I occasionally got the following exception, right after starting a test:
> 
>     Traceback (most recent call last):
>     File "/usr/libexec/stbt/stbt-run", line 50, in <module>
>       execfile(args.script)
>     [...]
>     File "/usr/libexec/stbt/stbt.py", line 349, in detect_match
>       for sample in _display.gst_samples(timeout_secs):
>     File "/usr/libexec/stbt/stbt.py", line 1253, in gst_samples
>       sample = self.get_sample(max(10, timeout_secs))
>     File "/usr/libexec/stbt/stbt.py", line 1237, in get_sample
>       raise UITestError(str(gst_sample))
>     UITestError: Internal data flow error.: Internal data flow error.
>     gstbasesrc.c(2812): gst_base_src_loop ():
>     /GstPipeline:pipeline1/GstAppSrc:appsrc:
>     streaming task paused, reason not-negotiated (-4)

This is with the HDPVR and the following stbt.conf:

    [global]
    source_pipeline = v4l2src device=/dev/video0 ! tsdemux ! h264parse
    sink_pipeline = xvimagesink sync=false
    restart_source = true

**Comment by drothlis** [comment]
Closing as per @szemate's [comment|#issuecomment-44260779]. Thanks for the report.
