### ISSUE TITLE
Occasional segfault during teardown with VidiU and GStreamer 1.0

### ISSUE THREAD

**Issue by drothlis** [drothlis/stb-tester#150]
Backtrace reported by @LewisHaley:

    Thread 1 (Thread 0x7fa57cc5a700 (LWP 16740)):
    #0  0x00007fa57fdee3a4 in RTMP_ReadPacket () from /lib64/librtmp.so.1
    #1  0x00007fa57fdf2667 in RTMP_GetNextMediaPacket () from /lib64/librtmp.so.1
    #2  0x00007fa57fdf2778 in Read_1_Packet () from /lib64/librtmp.so.1
    #3  0x00007fa57fdf31ec in RTMP_Read () from /lib64/librtmp.so.1
    #4  0x00007fa5841da36a in gst_rtmp_src_create () from /usr/lib64/gstreamer-1.0/libgstrtmp.so
    #5  0x00000030aa42ac7e in gst_base_src_get_range () from /lib64/libgstbase-1.0.so.0
    #6  0x00000030aa42c74b in gst_base_src_loop () from /lib64/libgstbase-1.0.so.0
    #7  0x00000030aa090559 in gst_task_func () from /lib64/libgstreamer-1.0.so.0
    #8  0x00000035cc86f406 in g_thread_pool_thread_proxy () from /lib64/libglib-2.0.so.0
    #9  0x00000035cc86ea45 in g_thread_proxy () from /lib64/libglib-2.0.so.0
    #10 0x00000035ca807f33 in start_thread () from /lib64/libpthread.so.0
    #11 0x00000035ca0f4ded in clone () from /lib64/libc.so.6

This happens about 3% of test runs. It happens during the pipeline
teardown, and the test run is otherwise successful. (It's still annoying
though because the test run gets reported as an error, and the recorded
video isn't seekable.)

**Comment by drothlis** [comment]
Closing upstream GStreamer / librtmp bugs that we don't intend to fix since it doesn't affect the hardware we use.
