### ISSUE TITLE
Selftest intermittent failure: test_that_virtual_remote_is_symmetric_with_virtual_remote_listen

### ISSUE THREAD

**Issue by drothlis** [drothlis/stb-tester#236]
https://travis-ci.org/drothlis/stb-tester/builds/40982063 :

    ERROR: _stbt.control.test_that_virtual_remote_is_symmetric_with_virtual_remote_listen
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
    File "/home/travis/build/drothlis/stb-tester/_stbt/control.py", line 519, in test_that_virtual_remote_is_symmetric_with_virtual_remote_listen
    vr = uri_to_remote('vr:localhost:2033')
    File "/home/travis/build/drothlis/stb-tester/_stbt/control.py", line 40, in uri_to_remote
    return factory(**m.groupdict())
    File "/home/travis/build/drothlis/stb-tester/_stbt/control.py", line 123, in __init__
    self._connect()
    File "/home/travis/build/drothlis/stb-tester/_stbt/control.py", line 132, in _connect
    return _connect_tcp_socket(self.hostname, self.port)
    File "/home/travis/build/drothlis/stb-tester/_stbt/control.py", line 437, in _connect_tcp_socket
    s.connect((address, port))
    File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
    error: [Errno 111] Failed to connect to remote control at localhost:2033: [Errno 111] Connection refused

**Comment by drothlis** [comment]
I haven't seen this in a while; closing.
